Exam
julia-ste/2022-2-VK-EDU-FS-Frontend-J-Stepanova pull request #7
Opened 2022-12-29 18:56 UTC by julia-ste

- [ ] В корневой папке репозитория создать базовое приложение `exam` с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) по инструкции выше
- [ ] Сверстать 2 страницы и необходимые компоненты. Использовать стили
- [ ] Реализовать перевод с одного языка на другой (хорошо, если можно будет выбрать язык из выпадающего списка)
- [ ] Реализовать перевод с неизвестного языка (автоопределитель из `API`)
- [ ] Сохранять историю переводов в `localStorage`
- [ ] Использовать `Redux`
- [ ] Использовать `React-router` для перехода между страницами
- [ ] Задеплоить решение, используя `GitHub Actions`.
- [ ] Теория: Объяснить, почему были использованы те или иные инструменты, участки кода и механизмы при решении задачи. Ответить на теоретические вопросы (пункт выполняется лично с преподавателем)
- [ ] Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно)

2022-12-29 19:06 UTC, HaseProgram commented on exam/src/components/TextBox/TextBox.jsx
> +    const [text, setText] = useState(initialText)
const [lang, setLang] = useState('ru')

2022-12-29 19:07 UTC, HaseProgram commented on exam/src/components/TextBox/TextBox.jsx
> +
```JavaScript
useEffect(() => {

}, [lang, text])
```

2022-12-29 19:08 UTC, HaseProgram commented on exam/src/components/TextBox/TextBox.jsx
> +
https://learn.javascript.ru/task/debounce

2022-12-29 19:10 UTC, HaseProgram commented on exam/src/components/TextBox/TextBox.jsx
> +
sortComments - передавать из внешнего компонента
onChange для textarea тоже передавать из внешнего компонента (только для левого поля)

2022-12-29 19:12 UTC, HaseProgram commented on exam/src/components/TextBox/TextBox.jsx
> +                disabled={disabled}
disabled={!!onChange}

2022-12-29 19:22 UTC, HaseProgram requested changes
Доделать пункты, сделать так, чтобы приложение запускалось и работало, чтобы было задеплоено. Как будет сделано тэгнуть для финальной проверки

2022-12-30 20:03 UTC, julia-ste commented
@HaseProgram готово

2022-12-31 14:08 UTC, HaseProgram approved these changes
Зачет, 40!

2022-12-31 14:08 UTC, merged